### ISSUE TITLE
Model of Ivermectin as prevention

### ISSUE THREAD

**Issue by KeithCu** [TheMemeticist/Cellular-Defense-Automata#4]
There's quite a lot of evidence that Ivermectin as prevention / treatment can stop viral replication and end the pandemic better than a mass vax campaign:
https://flccc.substack.com/p/summary-of-the-evidence-for-ivermectin?r=nxypy&utm_campaign=post&utm_medium=web&utm_source=copy

Can you please model that option?

**Comment by TheMemeticist** [comment]
Added the damn horse pills.

Issue closed.
